In [14]:
#31.Create a list of tuples from given list having number and its cube in each tuple
lst=[2,3,4,5]
newlist=[]
for i in lst:
    c=i**3
    newlist.append((i,c))
print(newlist)

[(2, 8), (3, 27), (4, 64), (5, 125)]


In [1]:
#32.Sort Python Dictionaries by Key or Value
myDict = {'ravi': 10, 'rajnish': 9,
        'sanjeev': 15, 'yash': 2, 'suraj': 32}
 
myKeys = list(myDict.keys())
myKeys.sort()
sorted_dict = {i: myDict[i] for i in myKeys}
 
print(sorted_dict)

{'rajnish': 9, 'ravi': 10, 'sanjeev': 15, 'suraj': 32, 'yash': 2}


In [2]:
#33.Python dictionary with keys having multiple inputs
places = {("19.07'53.2", "72.54'51.0"):"Mumbai", \
          ("28.33'34.1", "77.06'16.6"):"Delhi"}
print(places)
print('\n')
lat = []
long = []
plc = []
for i in places:
    lat.append(i[0])
    long.append(i[1])
    plc.append(places[i[0], i[1]])
 
print(lat)
print(long)
print(plc)

{("19.07'53.2", "72.54'51.0"): 'Mumbai', ("28.33'34.1", "77.06'16.6"): 'Delhi'}


["19.07'53.2", "28.33'34.1"]
["72.54'51.0", "77.06'16.6"]
['Mumbai', 'Delhi']


In [4]:
#34.Python program to find the sum of all items in a dictionary
dict = {'a': 100, 'b': 200, 'c': 300}
list=[]
for i in dict:
    list.append(dict[i])
final=sum(list)
print("Sum :",final)

Sum : 600


In [5]:
#35.Python program to find the length of a dictionary
dict1 ={'Name':'Steve', 'Age':30, 'Designation':'Programmer'}
print("Dictionary:", dict1)
print("Length of dictionary:", len(dict1))

Dictionary: {'Name': 'Steve', 'Age': 30, 'Designation': 'Programmer'}
Length of dictionary: 3


In [7]:
#36.Find the length of a set in python
set1=set()
set1.add(8)
set1.add(9)
set1.add((6,7))
print("Length=",len(set1))

Length= 3


In [8]:
#37.Iterate over a set in python
test_set = set("geEks")
for val in test_set:
    print(val)

k
s
E
e
g


In [9]:
#38.Maximum and Minimum in a Set
sets=set([8,16,24,1,25,3,10,65,55])
print(max(sets))
print(min(sets))

65
1


In [10]:
#39.Remove items from set
def Remove(initial_set):
    while initial_set:
        initial_set.pop()
        print(initial_set)
initial_set = set([12, 10, 13, 15, 8, 9])
Remove(initial_set)

{9, 10, 12, 13, 15}
{10, 12, 13, 15}
{12, 13, 15}
{13, 15}
{15}
set()


In [1]:
#40.Check if two lists have atleast one element common
def common_member(a, b):
    a_set = set(a)
    b_set = set(b)
    if (a_set & b_set):
        return True
    else:
        return False

a = [1, 2, 3, 4, 5]
b = [5, 6, 7, 8, 9]
print(common_member(a, b))

a =[1, 2, 3, 4, 5]
b =[6, 7, 8, 9]
print(common_member(a, b))


True
False


In [1]:
#41.Python – Assigning Subsequent Rows to Matrix first row elements
test_list = [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
print("The original list : " + str(test_list))
a=test_list[0]
b=test_list[1:len(test_list)]
d=dict()
for i in range(0,len(a)):
    d[a[i]]=b[i]
print("The Assigned Matrix : " + str(d))

The original list : [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
The Assigned Matrix : {5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


In [1]:
#42.Adding Matrices in Python
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [2]:
#43.Subtracting Matrices in Python
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Subtraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [3]:
#44.Group similar elements into Matrix
from itertools import groupby
test_list = [1, 3, 5, 1, 3, 2, 5, 4, 2]
print("The original list : " + str(test_list))
res = [list(val) for key, val in groupby(sorted(test_list))]
print("Matrix after grouping : " + str(res))

The original list : [1, 3, 5, 1, 3, 2, 5, 4, 2]
Matrix after grouping : [[1, 1], [2, 2], [3, 3], [4], [5, 5]]


In [4]:
#45.Create an n x n square matrix, where all the sub-matrix has the sum of opposite corner elements as even
import itertools
def sub_mat_even(n):
    temp = itertools.count(1)
    l = [[next(temp)for i in range(n)]for i in range(n)]
    if n%2 == 0:
        for i in range(0,len(l)):
            if i%2 == 1:
                l[i][:] = l[i][::-1]
    for i in range(n):
        for j in range(n):
            print(l[i][j],end=" ")
        print()
n = 4
sub_mat_even(n)


1 2 3 4 
8 7 6 5 
9 10 11 12 
16 15 14 13 


In [5]:
#46.How to get list of parameters name from a function in Python
import inspect
import collections
print(inspect.signature(collections.Counter))

(iterable=None, /, **kwds)


In [6]:
#47.How to Print Multiple Arguments in Python
def GFG(name, num):
    print("Hello from ", name + ', ' + num)
GFG("geeks for geeks", "25")

Hello from  geeks for geeks, 25


In [7]:
#48.Python program to find the power of a number using recursion
def power(N, P):
    if P == 0:
        return 1
    return (N*power(N, P-1))
if __name__ == '__main__':
    N = 5
    P = 2
    print(power(N, P))


25


In [8]:
#49.Sorting objects of user defined class in Python
class GFG:
    def __init__(self, a, b):
        self.a = a
        self.b = b
    def __repr__(self):
        return str((self.a, self.b))
gfg = [GFG("geeks", 1),
    GFG("computer", 3),
    GFG("for", 2),
    GFG("geeks", 4),
    GFG("science", 3)]
print(sorted(gfg, key=lambda x: x.b))

[('geeks', 1), ('for', 2), ('computer', 3), ('science', 3), ('geeks', 4)]


In [9]:
#50.Functions that accept variable length key value pair as arguments
def printKwargs(**kwargs):
    print(kwargs)
if __name__ == "__main__":
    printKwargs(Argument_1='gfg', Argument_2='GFG')

{'Argument_1': 'gfg', 'Argument_2': 'GFG'}
